### ISSUE TITLE
Respect user specified platform and configuration

### ISSUE THREAD

**Issue by jeffkl** [jeffkl/SlnGen#11]
At the moment, we hard code the Platform and Configuration when generation a solution file.  We should read the values from the project and use those instead.

https://github.com/jeffkl/SlnGen/blob/a25b47386ed6596607d9799ee7632b2f497c956c/src/SlnGen.Build.Tasks/Internal/SlnFile.cs#L60

**Comment by amrmahdi** [comment]
@jeffkl I was thinking this could be defined as SlnGen properties, like SlnGenPlatforms/SlnGenConfigurations since when you are building a project there is only 1 platform configuration, but the solution could have multiple options. What do you think ?

**Comment by jeffkl** [comment]
Yeah ideally we'd read the project's configuration/platform and then allow for properties to define the total set of configuration/platforms.

**Comment by amrmahdi** [comment]
I settled on reading them directly from Projects configs, same behavior as VS. Didn't make a lot of sense the idea of globally overriding the configurations.

**Comment by esouvik** [comment]
This fix is honoring values from Project files. But if user provide Platform and Configuration as msbuild parameter, it should override the values from Project files and honor the parameter

**Comment by amrmahdi** [comment]
I've a change where it adds the configured Configuration/Platform. But for non SDK style projects, Visual Studio does not seems to honor these configurations even though we have added it to the solution. I found that it only works if it is defined as conditioned property as <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|x64' " /> for example. Not sure how to overcome this issue from a solution perspective, I think we can't. 

@esouvik What is the types of projects you are using, SDK style, or legacy style ? Can you post some details and example project about your use case ?

**Comment by esouvik** [comment]
Ours are legacy style. 
What I meant is if we use 
msbuild /t:slngen /property:Platform=x64

Dirs.sln should have-
GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|x64 = Debug|x64
		Release|x64 = Release|x64

Currently it is honoring what is inside the all the proj files and outputting-
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|AnyCPU = Debug|AnyCPU
		Debug|x64 = Debug|x64
		Debug|Win32 = Debug|Win32
		Debug|x86 = Debug|x86
		Debug|Itanium = Debug|Itanium
		Debug|amd64 = Debug|amd64
		Release|AnyCPU = Release|AnyCPU
		Release|x64 = Release|x64
		Release|Win32 = Release|Win32
		Release|x86 = Release|x86
		Release|Itanium = Release|Itanium
		Release|amd64 = Release|amd64

**Comment by amrmahdi** [comment]
As I mentioned, even if the solution is generated with your provided platform, and this platform is not defined as <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|x64' " /> for example, visual studio will show it in the drop down of the configuration, but will not build using it.

**Comment by esouvik** [comment]
About the build failure, that is true with the current behavior too. For example out of 50 project in one project there is a condition like below, it is creating an item like Debug|Win32 = Debug|Win32, and build will fail if user select that. Instead if this can honor the parameter from command prompt, then its teams responsibility to make the build right for that platform that they are giving as a param. I think it would be a easy fix and will be very helpful

<PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|Win32'">
    ...
  </PropertyGroup>

**Comment by amrmahdi** [comment]
Agreed. The best we can do is to add the property values, an it should be the developer responsibility to setup the projects with the right combination of configuration|platform.

**Comment by esouvik** [comment]
Thank you for fixing this. Please let me know when latest version is available

**Comment by jeffkl** [comment]
I've deployed the package, it will show up soon

https://www.nuget.org/packages/SlnGen/2.0.27-beta

https://github.com/jeffkl/SlnGen/releases/tag/2.0.27

**Comment by esouvik** [comment]
I could not make this work. Tried this-
msbuild /t:SlnGen /property:Platform=x64

**Expected:**
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|x64 = Debug|x64
		Release|x64 = Release|x64

**Actual is:**
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|x64 = Debug|x64
		Debug|AnyCPU = Debug|AnyCPU
		Release|x64 = Release|x64
		Release|AnyCPU = Release|AnyCPU

**Comment by amrmahdi** [comment]
This is the expected behavior as you must have AnyCPU as ConditionedProperty in your csproj. Now as long as the configurations you defined is in the solution, why doesn't it work for you ?

**Comment by esouvik** [comment]
I think this is what we discussed- if user provide anything on Command line that will override every other thing. In this case user has given x64, it should not generate anything like "AnyCPU" whether its there in project or not. 
Just like MSBuilkd does, if user use x64, it builds with x64, and does not look whats there in Project as default.
Probably I misunderstood, but I thought this is the fix we are making here.

**Comment by jeffkl** [comment]
@esouvik when Visual Studio opens, is x64 the default selected value in Configuration Manager?  If it is, that seems like its what you want.  The generated solution files are generally throw anyway.

**Comment by esouvik** [comment]
No, it didnt open with x64, it opened with AnyCPU as default.

**Comment by jeffkl** [comment]
Dang, it must use sort alphabetically and use the first :(

We can see if there's a way to set the default in the solution file or add a property to indicate you want to ignore conditioned properties.  If you only want x64, you really shouldn't have AnyCPU in your projects...

**Comment by esouvik** [comment]
I assume its much easier for you to make as following just honoring command line param if provided, ignoring project detail, we have many junks in project files thats why this feature is so important to honor command line

GlobalSection(SolutionConfigurationPlatforms) = preSolution
Debug|x64 = Debug|x64
Release|x64 = Release|x64
