### ISSUE TITLE
SlnGenLaunchVisualStudio default value

### ISSUE THREAD

**Issue by jp2masa** [jeffkl/SlnGen#36]
The default value of [`SlnGenLaunchVisualStudio` is `true`](https://github.com/jeffkl/SlnGen/blob/master/src/SlnGen.Build.Tasks/build/SlnGen.targets#L32), but the docs refer that the [default value is `false`](https://jeffkl.github.io/SlnGen/#launching-of-visual-studio), so one of those has to be fixed.

**Comment by jeffkl** [comment]
Thanks, I fixed it

https://github.com/jeffkl/SlnGen/commit/4ccec92d4f2fa2927d0acc38c97f86599526813e#diff-e70100059cc3a7376740bbe9751a082e
