### ISSUE TITLE
Check the "Deploy" box by default in solution configuration.

### ISSUE THREAD

**Issue by majastrz** [jeffkl/SlnGen#53]
Is it possible to have SlnGen enable the "Deploy" option in solution configuration for specific projects? 

We have some service fabric projects (sfproj) in our repo. When we generate an sln with SlnGen, the "Deploy" option is disabled. When deploying the app to a local cluster (set project as startup, F5), you have to open solution config and check the box every time, which is kind of annoying :(

**Comment by jeffkl** [comment]
Do you know what changes in the solution file change this setting?  That would help a lot!

**Comment by majastrz** [comment]
It seems to the bold part to the sln. 

```
Global
...
    GlobalSection(ProjectConfigurationPlatforms) = postSolution
        ...
        {D8DE1A65-A9A6-476E-B88B-2655E2A7FF44}.Debug|x64.ActiveCfg = Debug|x64
        {D8DE1A65-A9A6-476E-B88B-2655E2A7FF44}.Debug|x64.Build.0 = Debug|x64
        **{D8DE1A65-A9A6-476E-B88B-2655E2A7FF44}.Debug|x64.Deploy.0 = Debug|x64**
        ...

**Comment by jeffkl** [comment]
Awesome thanks.  Looks like we just need to write out a line after here:

https://github.com/jeffkl/SlnGen/blob/master/src/SlnGen.Build.Tasks/Internal/SlnFile.cs#L179

If its a `.sfproj`

**Comment by majastrz** [comment]
That would work for me, but I believe that the "Deploy" thing is generic and would light up for projects that have Publish or Deploy targets (I forget what they're called.) I think, website projects, deployment projects, and probably cloud service project would also have it.

Defaulting on sfproj makes sense to me, but I wonder if this should be a property that you set in the project that tells SlnGen to turn it on for that particular one. This way I would probably just set that to true in Directory.Build.props if project extension is .sfproj and other people could do whatever makes sense for their repo.

**Comment by jeffkl** [comment]
Yes that's a good point.  If you can figure out what property to read that indicates if a project is "deployable" we should use that.

**Comment by majastrz** [comment]
I don't see anything obvious in sfproj. This could be a query made to the project system inside VS through one of the extensibility interfaces and not just an msbuild thing. (Project systems in VS don't necessarily have to use MSBuild) Or they're keying off a presence of some target like "Publish", but that would be hard to validate without looking at all projects that support it.

The safest thing could be to just add an extra SlnGen specific property that lets you turn it on.

**Comment by majastrz** [comment]
> Awesome thanks. Looks like we just need to write out a line after here:
> 
> https://github.com/jeffkl/SlnGen/blob/master/src/SlnGen.Build.Tasks/Internal/SlnFile.cs#L179
> 
> If its a `.sfproj`

@jeffkl, would you be ok with this fix for now until we figure out a way to autodetect this?

**Comment by jeffkl** [comment]
Yes that would probably be a good idea anyway in case the auto-detection logic wasn't correct people always need an escape hatch.
