### ISSUE TITLE
Solution with a mix of .Net Standard and .Net Framework causes VS 2019 to hang

### ISSUE THREAD

**Issue by johnthcall** [jeffkl/SlnGen#71]
Using version 2.2.27 of SlnGen the solution generated causes VS to hang. I have reported the hang to the VS team [here](https://developercommunity.visualstudio.com/content/problem/798634/solution-with-net-standard-library-freezes.html) 

I later found that by removing the .Net Standard libraries from the solution file I was able to open solution and manually add the libraries reorders the solution and causes it to load properly on cold start. Attached the solution file that works and the one that is generated. I am MSFT internal so let me know if you want me to share the repository and branch as a repro.

[solutionFiles.zip](https://github.com/jeffkl/SlnGen/files/3790103/solutionFiles.zip)

**Comment by jeffkl** [comment]
Release available here: https://www.nuget.org/packages/SlnGen/2.2.29
